### ISSUE TITLE
Holodoodler doesn't work with Orthomosaics

### ISSUE THREAD

**Issue by 2320sharon** [pyviz-topics/holodoodler#15]
# Holodoodler doesn't work with Orthomosaics
Orthomosaics will not display on holodoodler no matter what size they are. They also cannot have their segmentations saved as when you click to save the segmentation it throws an error message which I have posted a portion of below. I have gleaned from the error message that it is because the jpgs have an alpha channel that is not supported by Pillow. I'm guessing the solution is to convert them to pngs but I'm not sure.

![holodooder_ortho_issue](https://user-images.githubusercontent.com/61564689/148605979-79d2e49e-531b-466b-8234-cf321ce4000e.png)

## Error Message
The following error message was discovered when I attempted to save a segmentation from one of these Orthomosaics.

```
Traceback (most recent call last):
...
  File "C:\Users\Sharon\anaconda3\envs\doodler-dev\lib\site-packages\imageio\core\format.py", line 495, in append_data
    return self._append_data(im, total_meta)
  File "C:\Users\Sharon\anaconda3\envs\doodler-dev\lib\site-packages\imageio\plugins\pillow_legacy.py", line 538, in _append_data
    `raise IOError("JPEG does not support alpha channel.")`
OSError: JPEG does not support alpha channel.
```

# Orthomosaics
This is a subset of the Orthomosaics I tested Holodoodler with. Hope it helps with fixing the bug.

![2018-12-LittleDauphinIsland-ortho-rgb-5cm_04_05](https://user-images.githubusercontent.com/61564689/148605756-99e66736-80a5-4aca-a963-3fcf88cb3990.jpg)
![2018-12-LittleDauphinIsland-ortho-rgb-5cm_08_06](https://user-images.githubusercontent.com/61564689/148605760-65d8a1c5-53cb-4b63-bfb0-a7fd2185d049.jpg)
![20180619_MadeiraBeachFL_ortho_5cm_03_01](https://user-images.githubusercontent.com/61564689/148605761-d3a5356f-8631-4796-9737-498eeb1353ff.jpg)

**Comment by jbednar** [comment]
That error message results from using Pillow to save an image that has an alpha channel defined. In theory, JPG has some support for alpha channels, but it's almost unused and very poorly supported, so in this case we can either strip the alpha channel before saving, or export to PNG rather than JPG.  For these images I'm guessing the alpha channel is important because it shows the edge of the actual image area, and so you wouldn't want to discard it?

**Comment by dbuscombe-usgs** [comment]
Thanks @jbednar that makes complete sense. We do encounter a lot of imagery that when converted from geoTIFF to JPG suffers from this problem. I think we can safely strip the alpha channel; I think the resulting images would encode alpha (no data) as 0, and the Doodler classification algorithms would be ok with that. In fact, that is what it currently expects. If the underlying image value is 0, then the label assigned to that pixel is automatically 0, and 0 is interpreted as no data

We could also use PNG, but my preference would be to explore stripping alpha from JPG first, only because JPG is what we opted for the original. Agile code that could accept either JPG or PNG would also be great

**Comment by maximlt** [comment]
Thanks for reporting this bug @2320sharon !

I've stripped the extra 4th band in this [commit](https://github.com/pyviz-topics/holodoodler/commit/24be2e7e0cb5a2121edc945a0624800dc3e46d29).
