### ISSUE TITLE
"A task has failed to un-serialize"

### ISSUE THREAD

**Issue by dbuscombe-usgs** [pyviz-topics/holodoodler#16]
I added some classes to config like so

```
[classes]
sand=#914e09
water=#0f5e9c
road=#B91FDE
herb_veg=#2BDE1F
wood_veg=#0B5206
```

and doodled this image

![holodoodler-unserialize-error](https://user-images.githubusercontent.com/3596509/148791146-fb74ed50-bcd9-487a-9803-82a23a3ba920.PNG)

which gave me the following terminal output 

[holodoodler-error.txt](https://github.com/pyviz-topics/holodoodler/files/7839895/holodoodler-error.txt)

Offending image here

![2020-0504-0505_DSS_vegAOI_ortho_UTM-NAD83+NAVD88_TPA1 0_02_06](https://user-images.githubusercontent.com/3596509/148791390-9634d067-ff19-4989-b0f4-b3708a5cfb51.jpg)

**Comment by dbuscombe-usgs** [comment]
To try to troubleshoot, I removed the extra classes, then doodled the 'example1.jpg` - this resulted in the same error.

I then removed the extra images, resulting in the original configuration, with the original images, and same error again

I have now reverted to the original set of files and config file, but I'm getting the same error. In other words, I seem to have broken my version of the program somehow by adding images and/classes

**Comment by dbuscombe-usgs** [comment]
Update, I tried accessing the Panel version

```
panel serve doodler.ipynb --show
```

on Microsoft Edge instead of Chrome, and I'm getting the same error

everything was working fine on chrome and edge before I attempt to doodle a different image and modify the config file. What is strange is that now I'm using the original images and config file, but something appears to be broken on my installation.

**Comment by dbuscombe-usgs** [comment]
I deleted all the notebook checkpoints but am still getting the same error. 

Then, I re-cloned the repo, so I'm working with the original files, but didnt re-create the conda environment. Same errors. 

Somehow, it seems that the act of adding images and / or modifying the config file has broken my conda environment (?) I will now nuke the conda environment and reinstall it

**Comment by maximlt** [comment]
Oh no I'm also seeing that. Will try to fix it before the meeting! Thanks for also looking into it, these are good pointers!

**Comment by maximlt** [comment]
I pushed a commit that adds this code before the imports and that seems to fix the issue:
```
# Hack from https://github.com/facebook/prophet/issues/1889
import multiprocessing
multiprocessing.set_start_method("fork")
```

I'm going to keep this issue opened anyway because it's clearly a hack and it needs more investigation.

**Comment by 2320sharon** [comment]
@maximlt 
This hack won't work with Windows because Windows doesn't have a fork function. My Windows machine has been able to add, remove, modify the config and images file with no problems, so this issue might be specific to Unix machines.

https://docs.python.org/3/library/multiprocessing.html#:~:text=The%20parent%20process%20uses,The%20default%20on%20Unix.

**Comment by dbuscombe-usgs** [comment]
I should have mentioned, all of my issues were on windows. I haven't yet tested on Linux

**Comment by maximlt** [comment]
Thanks @2320sharon for digging into that. It definitely needs more investigation 🤔 I experienced this issue on a Mac.

What surprises me too is that I never had this issue before the recent changes. I'll try to see if I can reproduce the issue based on an older commit, I don't think I made a single change that touched the core algorithmic part of the code, where I have the impression that the error comes from.

**Comment by maximlt** [comment]
So after a little more digging on this issue I've found a way to at least partially fix the issue. `joblib`, a library that is used by the core algorithm of Doodler to launch parallel computations, seems not to play well with the panel/bokeh/tornado setting. I've managed to run the code from a script without getting the same error. Which one of these packages was responsible for the bug? Difficult to say without spending more time on it. It could also have been the way `joblib` was called or its setting.

Anyway, I've added `prefer='threads'` to the calls made by `joblib` to set it to use its 'threading' backend instead of its default 'loky' one (custom multiprocessing). Why?
* Because with this option the bug was gone :)
* But also because the operations done by the functions called by `joblib` are likely to release the GIL (e.g. numpy operations) and threading should improve the performance in this context. I've also observed that it made the computation faster on the example I was trying (from 20s to 10s).

Now to be honest I've also tried to set `n_jobs` to 1 which means that only 1 worker is used (no more parallelism) and the computation time was about the same as with threading. If this hasn't already be done it'd be interesting to do some investigation and optimization in this area. Reading `joblib`'s documentation I see that they provide a context manager that allows to set at one point the parameters of the calls such as `n_jobs` and `prefer`. This is nice if the settings end up being configurable (to cope with different contexts), the settings could be defined in a config file, read and applied by `app.py` when it calls the core algorithm.

Last point, to reproduce the bug the following condition has to be true at runtime if not `joblib` is bypassed: 
```python
    if (psutil.virtual_memory()[0] > 10000000000) & (psutil.virtual_memory()[2] < 50):  # >10GB and <50% utilization
```

**Comment by dbuscombe-usgs** [comment]
Just tried latest version on Linux and Windows. Everything works great on Linux. On Windows,  only works when I comment out

```
multiprocessing.set_start_method("fork")
```

then works great. Happy to provide more details 

I'll look into  benchmarking with threading versus no threading. Interesting observations, thanks for looking into it @maximlt !

**Comment by maximlt** [comment]
I think I know why, were you launching the app from the notebook (`panel serve doodler_nb.ipynb`)? If so, I had forgotten to remove the multiprocessing hack in the notebook. I've updated the README to indicate that the preferred option would be to now launch the app with `panel serve app.py`. If not, please let me know and I will reopen this issue.

**Comment by dbuscombe-usgs** [comment]
Incorrect. I had to remove `multiprocessing.set_start_method("fork")` to get either the `panel serve doodler_nb.ipynb` or the jupyterlab way to run...

I only just noticed the new file `app.py`

thanks for updating
