### ISSUE TITLE
Comments on holodoodler implementation

### ISSUE THREAD

**Issue by csherwood-usgs** [pyviz-topics/holodoodler#26]
This seems to work very well, and is pretty user-friendly. Overall, a nice implementation. Some comments:
* Real estate! As much of the screen as possible should be occupied by the image to minimize the need to zoom and pan. I recommend the panel to the left be made narrower and, if necessary, maybe some of the controls should be moved to another tab.
* I can't tell which label is active by looking at the buttons. I see they change, but still can't tell.
* When zooming manually, it is hard (impossible?) to recover the original image presentation. Maybe add the capability to reset to the original presentation?
* The documentation video has no sound (that I could here) and should be augmented with written user documentation.

**Comment by csherwood-usgs** [comment]
Ok...item 3 above is a non-issue...the reset icon at the bottom of the toolbar does that. But now:
* Is there a way to select and delete a line if you mis-doodle? I can't find that.

**Comment by csherwood-usgs** [comment]
Re: item 3. Consider changing the layout so the image takes up the full width of the window. That is the limiting factor in real estate...there is plenty of vertical room. Like:
![image](https://user-images.githubusercontent.com/1618995/170096525-ce273abc-9895-483b-972a-b1cc438b7f7b.png)
The detailed settings could be on a second tabbed page...you don't need to access them very often.

**Comment by maximlt** [comment]
@csherwood-usgs thanks for your feedback, that's very helpful!

> I can't tell which label is active by looking at the buttons. I see they change, but still can't tell

When a label is active the text label is in bold. I agree that this should be improved though.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/35924738/170216876-2328f3b5-acc1-4cc3-ad7a-71e18998cfa3.png">

> The documentation video has no sound (that I could here) and should be augmented with written user documentation.

This video was put up as a quick way to show the team the state of the app development and demonstrate its capabilities at a point in time. It wasn't really meant as documenting how to use the app (dashdoodler does that very well). I think the app itself needs to mature a little more before it's documented, the code however is documented with docstrings.

> Real estate! As much of the screen as possible should be occupied by the image to minimize the need to zoom and pan. I recommend the panel to the left be made narrower and, if necessary, maybe some of the controls should be moved to another tab.

I agree that the app should make better use of the available space, the first step would be to make the image/canvas responsive. I also like your suggestions about the layout of the app, but I'd be happy to get feedback too from users of dashdoodler whose layout is somewhat similar to this app. The app is built on top of Panel which provides [some default templates](https://panel.holoviz.org/reference/index.html#templates). They pretty much all share the same layout, with a header, a side bar and a main area. I've picked one of these templates because it is usually the easiest way to get an app that looks better than without any template, and I guess it also behaves better on different devices. As you suggest the app could have tabs to hide settings that aren't often changed, or it could be based on a custom template (not one of those provided by Panel) although this is more involved.

> Is there a way to select and delete a line if you mis-doodle? I can't find that.

Actually yes! You can see in the GIF below that lines can be deleted after they've been drawn. The UX could be improved, i.e. the cursor should change on hovering a line to indicate that an action can be made on the hovered line, but this is a change that needs to happen not in the app but somewhere deeper in the stack (in holoviews or bokeh I presume). I've also noticed that, if I draw lines in a give class/width, then switch the class or width and draw more lines, I no longer manage to delete the lines that were drawn with the previous class/width. This might be a bug in the app.

![example_edit_holodoodler](https://user-images.githubusercontent.com/35924738/170219665-9267b924-4108-4f0f-aff3-dc81153838f4.gif)

**Comment by csherwood-usgs** [comment]
@maximlt The canvas is now much bigger and that is nice, but weird things happen if the browser window is resized. Notice the buttons (I have 9 of them) have disappeared under the image, and the blue/gold/green buttons got wide and are also partially hidden. I have made some changed in the file-reading section...see new issue and pull request.
![image](https://user-images.githubusercontent.com/1618995/170359334-b2003b3f-99dc-43dc-8813-efa6e446f39b.png)

**Comment by maximlt** [comment]
@philippjfr have you already seen that? I've been able to reproduce it by resizing multiple times the browser window. I pinned it down to the use of a FlexBox layout to wrap the classes in the `Doodling options` section.

**Comment by csherwood-usgs** [comment]
Hi @maximlt and @phillippjfr - The recent changes to the interface (described above) make it broken for most users. It would be good to either restore the original functionality, or fix this bug so test users can work on the other issues. Thanks!

**Comment by maximlt** [comment]
Do you mean the bug you showed in the screenshot above? If so, does it happen right away? When I reproduced I had to resize the browser window multiple times to get it.

**Comment by csherwood-usgs** [comment]
That is true, and maybe it is workable now and this is not a high priority.
